### ISSUE TITLE
Train the model from M1 for M2

### ISSUE THREAD

**Issue by ro-ko** [zjunlp/KnowAgent#4]
Hi, I'm impressed with your great work.

I trained the base model M0 with D0 -> M1
Then I'm trying to train M1 with D1
It seems that the `train_lora.py` does not have training code for D1

How to train the peft model M1 with D1?

**Comment by LesileZ** [comment]
Thank you for your interest! I think you can refer  to `Self-Learning/train_iter.sh` to execute the training code.

**Comment by ro-ko** [comment]
Thank you for your answering my question, I checked the `train_lora_iter.py` in `Self-Learning/train_iter.sh`. 

But `train_lora_iter.py` does not have filtering and merging function with D0 and D1.
It iteratively trains twice with the same dataset.

Do you mean I should just refer to the part about loading the PEFT model from a local path?

**Comment by LesileZ** [comment]
I apologize for the confusion. Before training, you need to process the data using the scripts in`Self-Learning/traj_filter_merge.sh` and `Self-Learning/traj_reformat.sh`.  The results from `traj_reformat.sh` are the data for the latest training round.  You can refer to these scripts to filter and merge D0 and D1.  I hope this helps!

**Comment by ro-ko** [comment]
I'm training the M1 based on the code you mentioned, thank you. So, to create the D1 data, I need to train the model once using `train.sh`, right?

**Comment by LesileZ** [comment]
Yes, I think the steps should be as follows:

- Use D0 to train M1 (train.sh)
- Use M1 to generate D1

After that, you'll be able to create the D1 data.

**Comment by ro-ko** [comment]
Now, I fully understand. Thank you for your kind explanation!
