### ISSUE TITLE
Inquiry About Decision Knowledge Learning

### ISSUE THREAD

**Issue by siifish** [zjunlp/KnowAgent#5]
I want to express my sincere respect for your outstanding work on this library! The design and implementation of this project are truly impressive.

I encountered some confusion while using the library. Specifically, I would like to understand the **learning process for decision knowledge** within the library. My observation is that the code only includes sections for making decisions using manually constructed decision knowledge prompt, and I haven't found any code related to the learning aspect. Could you please provide some details or guidance regarding the implementation of decision knowledge learning? Because I saw a comparison between manually constructed decision knowledge and GPT-4 learning **in the paper**：

![image](https://github.com/user-attachments/assets/b488d98c-6435-41f7-8793-b7cb7921fbe4)

Thank you for taking the time to address my question, and I look forward to your response!

**Comment by LesileZ** [comment]
If you are confused about the decision knowledge learning process, I suggest referring to Section 3.3 of our paper for more details. In that section, we outline our approach to knowledgeable self-learning, which I believe aligns with what you mentioned. Specifically, we integrate action knowledge (including guidance) into the trajectory context to support this learning process.
