### ISSUE TITLE
Some problems in reproduction

### ISSUE THREAD

**Issue by HoranChen** [zjunlp/KnowAgent#6]
Hi, this is an excellent job.
I am trying to make a reproduction of this work, but have run into a few problems with the following:
1, I am limited by the access restrictions of the BingSearchAPI in Path Generation. Can I skip this step by using the data you have published on Google Drive? But there is no data for test in Google Drive.
2, Is the D0 data in traj_filter_merge.sh the data in Google Drive? How do I get my D1 data, I see someone asked the same question but I still don't understand, do I need to redo the Path Generation using M1?
3, How do I get the train_answer_v3_500_D0_D1.json in train_iter.sh?
4, How to evaluate? I checked the documentation for fastchat but still don't understand.

**Comment by LesileZ** [comment]
Hi, thank you for your interest in our work. Here are some clarifications that might help:
1. To reproduce our experimental results, the use of BingSearchAPI is necessary, as we rely on it to assist with external search information during the testing phase. The test data can be found in the `Path_Generation/hotpotqa_run/data/test` directory.
2. Yes, the D0 data in `traj_filter_merge.sh` corresponds to the data provided on Google Drive. To obtain D1, you will need to train the M1 model first using D0 and then redo the Path Generation using M1.
3. After obtaining D1, you can run `traj_merge_and_filter.sh` to generate the necessary data. Then, use` traj_reformat.sh` to convert this data into the required format for training, which is `train_answer_v3_500_D0_D1.json`.
4.  For evaluation, simply set `--mode` to `test` as specified in Planning Path Generation to execute the testing phase. We’re using FastChat only as a method to deploy the Local LangChain API.

**Comment by HoranChen** [comment]
Thank you very much for your reply, I have some more questions as follows:

1. when I get the M1, can I run ` python run_hotpotqa.py again --llm_name llama-2-13b --max_context_len 4000 --mode train --output_path ... /Self-Learning/trajs/` again to get the D1, do I need to execute other steps in this step?
2. After I run Path Generation to execute the testing phase, will I be able to get the scoring results presented in the paper directly, or do I need to execute another scoring calculation process?

**Comment by LesileZ** [comment]
OK.
1. In this step, you can run traj_merge_and_filter.sh to generate the necessary data. Afterward, use traj_reformat.sh to convert this data into the required format for training, which is train_answer_v3_500_D0_D1.json. Once that's done, you can use train_iter.sh to generate the model for the next iteration.
2. Yes, the scoring results will be shown in the output file.

**Comment by HoranChen** [comment]
Thanks.
But I run `python alfworld_run/run_alfworld.py --llm_name llama-2-13b --mode train --output_path . /Self-Learning/trajs/` to generate the easy, middle, and hard json outputs, but I didn't find the scoring results.QAQ

**Comment by LesileZ** [comment]
Sorry, I didn't explain it clearly. You can calculate the values for this part based on the final output following the code in 
[BOLAA](https://github.com/salesforce/BOLAA/blob/5f1a6e04150b436b11a43a8b5510466b22b53840/hotpotqa_run/evaluate.py).

**Comment by HoranChen** [comment]
Thank you very much for your reply, I understand the whole process now.
But due to the limitation of Bing API, I can't get the D1, would you mind sharing the D1 in your experiments?
I promise I'll only use it for research purposes. Looking forward to your reply:)

**Comment by LesileZ** [comment]
We have made the updates on Google Drive, and you can find the files you need there.
