### ISSUE TITLE
The evaluation result of llama-2-7b-chat-M2 in HotpotQA

### ISSUE THREAD

**Issue by HoranChen** [zjunlp/KnowAgent#8]
Hi, I have reproduced the whole process using **llama-2-7b-chat**. When I get the **M2** model, the one in **HotpotQA-easy** only gets an evaluation result of **30.28**. May I ask if this result is close to what you have tested using M2? How many more iterations of the training process do I need to repeat to get the results in the paper?

**Comment by LesileZ** [comment]
Could you share the reward and accuracy values corresponding to your test results?

**Comment by HoranChen** [comment]
Average reward : 0.3027777777777778
Average success : 0.24

**Comment by LesileZ** [comment]
Perhaps you could check whether the `_bingsearch` function in your code is working correctly (specifically, if the output file contains an excessive number of "Search error" messages).  I have reproduced the results on my side, and they appear to be normal. The results you're currently obtaining seem to be lower than expected.

**Comment by HoranChen** [comment]
Hahaha, sorry, it was caused by my bing api reaching its maximum number of uses!
