### ISSUE TITLE
KeyError: val1 and Error: duplicate object loc_bar_5_bar_6_bar_1_bar_30

### ISSUE THREAD

**Issue by jonuseleven** [zjunlp/KnowAgent#9]
Thank you for sharing such outstanding work. While training M1 on the Alfworld dataset, I encountered the following errors: KeyError: val1 and Error: duplicate object loc bar 5 bar 6 bar l bar 30. I have tried some solutions, but unfortunately, I haven’t been able to resolve these issues, which has left me quite puzzled.Could you point out what might be causing these problems?

**Comment by LesileZ** [comment]
It seems like the issue might be related to data processing. Could you provide more details about the training process?

**Comment by jonuseleven** [comment]
I used the llama2-7b model and ran 
`python alfworld_run/run_alfworld.py --llm_name llama2_7b --mode train --output_path ../Self-Learning/trajs/`
When I ran to a certain progress in Checking for solvable games..., 
`KeyError: 'val1‘`or `Unsolvable: 'val1' `appeared in many pddl files. 
Sometimes there was also `error: duplicate object 'loc_bar_0_bar_3_bar_0_bar_30'please check :constants and :objects definitions.`
Could you please give me some suggestions?

**Comment by jonuseleven** [comment]
I used the llama2-7b model and ran 
`python alfworld_run/run_alfworld.py --llm_name llama2_7b --mode train --output_path ../Self-Learning/trajs/`
When I ran to a certain progress in Checking for solvable games..., 
`KeyError: 'val1‘`or `Unsolvable: 'val1' `appeared in many pddl files. 
Sometimes there was also `error: duplicate object 'loc_bar_0_bar_3_bar_0_bar_30'please check :constants and :objects definitions.`
Could you please give me some suggestions?

**Comment by LesileZ** [comment]
May I ask if you are using the files within the Path_Generation/alfworld_run/alfworld directory when configuring the Alfworld environment? We have made some modifications to certain files there, so using the files directly from [ALFWorld](https://github.com/alfworld/alfworld) might cause errors.

**Comment by jonuseleven** [comment]
Thank you very much for your guidance, I have solved the above problem! By the way, do you mind sharing your D1 file on the alfworld dataset so that I can find other errors in my results and make relevant modifications?

**Comment by LesileZ** [comment]
Thank you for your interest in our work. We've updated the files on Google Drive for your convenience.
